### DISCUSSION TITLE
`session.get()` returns `None` on first load and refresh for some unknown reason.

### DISCUSSION THREAD

**Discussion by Grafcube** [actix/actix-extras#322] [Q&A]
I have a handler that is meant to check whether the user is signed in. I am also using leptos for ssr+hydration.
```rust
let id = match session.get::<String>("id") {
    // ---
}
```
I noticed that for whatever reason, `session.get()` returns a `None` whenever I first load the page or refresh it. It doesn't happen when I navigate to the page with client side navigation.

To debug this, I logged the `HttpRequest` for every call to this function. In every case where I expected a cookie, I found one in the request.

For more context:
- [The function itself](https://codeberg.org/grafcube/wordforge/src/commit/8e2648f85bdf789a315b7e8a674833dc2937b50b/api/src/account.rs#L11): This is called whenever I expect it to be called, but returns a `None` when it shouldn't.
- [The leptos server function (for ssr)](https://codeberg.org/grafcube/wordforge/src/commit/8e2648f85bdf789a315b7e8a674833dc2937b50b/ui/src/app.rs#L126): Essentially, this is the actual function registered as a route to actix. In order to have multiple ways to call the validate function, I separated it out and had this function forward the extractors to it (the details aren't relevant to the issue I think).

And finally, here are the `HttpRequests` that I logged:

When refreshing/first load:
```
HttpRequest HTTP/1.1 GET:/
      headers:
        "cache-control": "no-cache"
        "accept-encoding": "gzip, deflate, br"
        "cookie": "id=Whr1WYUouV9R3eKIeM0u93mvbdxrdfza9Yby0fB8nPRy1ZAf0CbJcYzE2o5SrZmkzEzGTqb4YXljbERFWgvhUc50pjD62iPFsL7dEcphLECtROtBwEOXxed6rP8%3D"
        "upgrade-insecure-requests": "1"
        "host": "localhost:3000"
        "dnt": "1"
        "sec-fetch-mode": "navigate"
        "connection": "keep-alive"
        "pragma": "no-cache"
        "user-agent": "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0"
        "accept-language": "en-GB,en-US;q=0.7,en;q=0.3"
        "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/jxl,image/webp,*/*;q=0.8"
        "sec-fetch-site": "cross-site"
        "sec-fetch-dest": "document"
```
When navigating to the page:
```
HttpRequest HTTP/1.1 POST:/server/validate17522352961494492587
      params: Path { path: Url { uri: /server/validate17522352961494492587, path: None }, skip: 36, segments: [("tail", Segment(8, 36))] }
      headers:
        "content-type": "application/x-www-form-urlencoded"
        "cookie": "id=Whr1WYUouV9R3eKIeM0u93mvbdxrdfza9Yby0fB8nPRy1ZAf0CbJcYzE2o5SrZmkzEzGTqb4YXljbERFWgvhUc50pjD62iPFsL7dEcphLECtROtBwEOXxed6rP8%3D"
        "host": "localhost:3000"
        "dnt": "1"
        "referer": "http://localhost:3000/"
        "sec-fetch-mode": "cors"
        "accept-language": "en-GB,en-US;q=0.7,en;q=0.3"
        "accept": "application/x-www-form-urlencoded"
        "connection": "keep-alive"
        "sec-fetch-dest": "empty"
        "sec-fetch-site": "same-origin"
        "user-agent": "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0"
        "origin": "http://localhost:3000"
        "accept-encoding": "gzip, deflate, br"
        "content-length": "0"
```
The cookie is in both requests but `session.get::<String>("id")` still returns `None` for the first one. Any help is appreciated, TIA.
