### ISSUE TITLE
Actix Identity anyhow error type is incompatible with actix_web::Error

### ISSUE THREAD

**Issue by 0xpr03** [actix/actix-extras#272]
The error type used by actix_identity is incompatible with acitx_web::Error, creating some annoying usability problems inside actix_web code.

## Expected Behavior
I can just perform
```rust
pub async fn foo(identity: Identity) -> Result<HttpResponse, actix_web::Error> {
    identity.id()?;
```

## Current Behavior
Above code will fail as id() will simply return anyhow::Error, which isn't convertible to actix_web::Error and also an indirect re-export of anyhow, which isn't that good of a choice for libraries to use (over thiserror for example).

## Possible Solution
Export some error type (not anyhow at best), that has an impl for actix_web::Error or can be easily converted. This was possible in earlier actix_identity.

## Steps to Reproduce (for bugs)

1. See code above

## Context

I've got to manually convert each invocation of identity.id() or create a super type that wraps all these errors, while still maintaining `impl ResponseError`.

## Your Environment

* Rust Version (I.e, output of `rustc -V`): 1.62.1
* Actix-* crate(s) Version:
```toml
actix = "0.13"
actix-web = "4"
actix-rt = "2"
actix-files = "0.6"
actix-identity = "0.5"
actix-session = { features = ["cookie-session"], version = "0.7" }
actix-threadpool = "0.3"
```
